#Coming soon
FROM python:3.11-alpine
RUN apk update
RUN apk add git

# FROM python:3.11-slim
# RUN apt-get update
# RUN apt-get install -y git

ENV NODE_NAME "node12"

WORKDIR /app

COPY . /app/

RUN git clone https://github.com/ObeyonRFS/ObeyonRFS

RUN python ObeyonRFS/install_edit.py

CMD python -u src/nodes/${NODE_NAME}.py